### ISSUE TITLE
Can't Post

### ISSUE THREAD

**Issue by FosDagger** [swizzler/swizzler#3]
I don't see any way to post to Twister using Swizzler, I am unsure if this is the current state of the application or if I have done something foolish during install. Everything works fine, logging in, viewing posts, tags, etc... but there is no text box for creating a new post anywhere I can find.

**Comment by thedod** [comment]
> I am unsure if this is the current state of the application or if I have done something foolish during install

I'm afraid "[it's not you, it's me](https://www.youtube.com/watch?v=2uAj4wBIU-8)" :flushed:. Worse: even the read-only client is not finished yet :construction:. As the README [currently] [says](https://github.com/swizzler/swizzler/blame/d959492b2b6882c2b5997f76cafeb1bf4ff36ad6/README.md#L13):

> The following functionality is missing before Swizzler becomes a full **read-only** version

Still the long term plan (probably months) is to enable full (or almost full) functionality (and perhaps [additional features](https://github.com/swizzler/swizzler/wiki/Ideas-for-features)), so I guess we can close this ticket.

> Everything works fine

That's mighty cool to hear. Thanks.
